### ISSUE TITLE
.DS_Storeファイルの削除

### ISSUE THREAD

**Issue by TakutoYoshikai** [Ohnao/.zshrc#1]
特にリポジトリに含める理由がないので、削除したほうがいいと思います。
僕はいつも.gitignoreファイルに.DS_Storeを登録しています

**Comment by Ohnao** [comment]
そうですね・・・普段から関係無いしいいかなと思って除外することをしていませんでしたが・・・関係無いものまでgit管理するのは問題ですね・・・ありがとうございます！
